### ISSUE TITLE
Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client

### ISSUE THREAD

**Issue by mythsunwind** [wireapp/wire-web-ets#1355] opened 2020-04-20 21:10 UTC
```
(node:26121) UnhandledPromiseRejectionWarning: Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at ServerResponse.setHeader (_http_outgoing.js:485:11)
    at ServerResponse.header (/home/jenkins/workspace/workspace/wire-web-ets_Deploy_dev/node_modules/express/lib/response.js:771:10)
    at ServerResponse.send (/home/jenkins/workspace/workspace/wire-web-ets_Deploy_dev/node_modules/express/lib/response.js:170:12)
    at ServerResponse.json (/home/jenkins/workspace/workspace/wire-web-ets_Deploy_dev/node_modules/express/lib/response.js:267:15)
    at ExpressAdapter.reply (/home/jenkins/workspace/workspace/wire-web-ets_Deploy_dev/node_modules/@nestjs/platform-express/adapters/express-adapter.js:23:57)
    at ExceptionsHandler.handleUnknownError (/home/jenkins/workspace/workspace/wire-web-ets_Deploy_dev/node_modules/@nestjs/core/exceptions/base-exception-filter.js:32:24)
    at ExceptionsHandler.catch (/home/jenkins/workspace/workspace/wire-web-ets_Deploy_dev/node_modules/@nestjs/core/exceptions/base-exception-filter.js:16:25)
    at ExceptionsHandler.next (/home/jenkins/workspace/workspace/wire-web-ets_Deploy_dev/node_modules/@nestjs/core/exceptions/exceptions-handler.js:15:20)
    at /home/jenkins/workspace/workspace/wire-web-ets_Deploy_dev/node_modules/@nestjs/core/router/router-proxy.js:12:35
    at runMicrotasks (<anonymous>)
(node:26121) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 505)
(node:26121) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by ffflorian** [comment] 2021-05-12 08:30
Can't reproduce.

**Comment by ffflorian** [comment] 2021-05-17 08:14
Now I can reproduce it.

**Comment by ffflorian** [comment] 2021-06-17 13:11
Probably fixed with https://github.com/wireapp/wire-web-ets/commit/b83eac894babbf77e1077a71baeda996d274ca6b.

**Closed** 2021-11-02 09:11 UTC
